# Generated by Django 2.1.2 on 2018-12-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zone_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='content_field',
            field=models.CharField(blank=True, db_column='content_field', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='type_field',
            field=models.CharField(blank=True, db_column='type_field', max_length=200, null=True),
        ),
    ]
