# Generated by Django 2.1.2 on 2018-12-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zone_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inout',
            name='indate',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='inout',
            name='outdate',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
