# Generated by Django 2.1.2 on 2018-12-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zone_manage', '0002_auto_20181218_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inout',
            name='log_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
