# Generated by Django 2.1.2 on 2018-12-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zone_manage', '0002_auto_20181222_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='parlot',
            name='par_location',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parlot',
            name='par_id',
            field=models.BigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='parlot',
            unique_together={('par_location', 'gar_num')},
        ),
    ]
