# Generated by Django 2.1.2 on 2018-12-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zone_manage', '0003_auto_20181223_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parlot',
            name='par_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
